export const UPDATE_PROVIDERS = "UPDATE_PROVIDERS";

export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_MULTIPLE_TO_CART = "ADD_MULTIPLE_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";

export const UPDATE_SERVICES = "UPDATE_SERVICES";
export const UPDATE_CURRENT_SERVICE = "UPDATE_CURRENT_SERVICE";
